import type { Metadata } from "next";
import Navbar from "@/components/NavbarCoponents/Navbar";
import Footer from "@/components/NavbarCoponents/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="min-h-screen flex flex-col bg-black text-slate-100 font-sans">
            <Navbar />
            <main className="flex-1 w-full mxo-auto">
                {children}
            </main>

            <Footer />
        </div>
    );
}
